[2주차] 유랄리 과제 제출합니다.
cmc-14th-web/ReactNativeStudy pull request #11
Opened 2023-12-07 03:27 UTC by coddingyun

### 1주차와 다른점
- 상태관리 라이브러리는 Zustand를 사용하였습니다.
- inline style 대신 StyleSheet를 사용하여 가독성을 높였습니다.

### 트러블 슈팅
- Bottom Tab위에 Bottom Sheet가 겹쳐지지 않아 Navigation밖에 Bottom Sheet를 두었음
- Bottom Sheet의 경우 background를 가지고 있어, Bottom Tab이 클릭되지 않는 문제가 발생하여 사용자가 Bottom Sheet를 아래로 내릴 때 아예 display: none으로 없애 버림
- Bottom Tab위에 플러스 버튼이 겹쳐지지 않아, 위치를 absolute로 두어 임의로 위치를 고정시켰고, isHome을 전역상태로 관리하여 홈과 세팅에서만 플러스버튼이 나타나도록 하였음

### 이슈
- IOS의 경우, 가장 처음(앱이 깔릴 때)에만 권한 요청을 하고, 설정에서 권한 해제 후에 다시 앱에 접근시 권한 요청을 하지 않음

### 비고
- 세팅 페이지는 요구사항에 없어 아무것도 채우지 않음

2023-12-08 06:19 UTC, nim-od requested changes

2023-12-08 06:19 UTC, nim-od commented on ReactNativeStudy/Eurali/Week2/cameraApp/src/App.tsx
> +  const isHome = useStore(state => state.isHome);
rootStack에 Tab Navigator 와 Detail photo screeen을 두고, Tab Navigator 내부에 addbutton을 위치시키면 isHome 없이 appbar button을 관리할 수 있습니다.

2023-12-08 06:19 UTC, nim-od commented on ReactNativeStudy/Eurali/Week2/cameraApp/src/App.tsx
> +        {/* <TabNavigation /> */}
주석 처리 되어있어요!

2023-12-08 06:19 UTC, nim-od commented on ReactNativeStudy/Eurali/Week2/cameraApp/src/components/AddButton.tsx
> +const {width} = Dimensions.get('window');
SCREEN_WIDTH 등으로 변수명 바꿔서 common constants 로 관리해도 좋을 것 같습니다.
@gorhom/bottom-sheet 내에서 자체적으로 제공하는 screen size 변수도 있더라고요.

2023-12-08 06:19 UTC, nim-od commented on ReactNativeStudy/Eurali/Week2/cameraApp/src/components/AddButton.tsx
> +  const handleClickAdd = () => {
저도 state 변경 시 한 줄이어도 handle~~로 처리하는 방식 선호합니다!

2023-12-08 06:19 UTC, nim-od commented on ReactNativeStudy/Eurali/Week2/cameraApp/src/components/BottomSheet.tsx
> +        onChange={handleSheetChanges}
저는 setIsClosed, onChange 등을 사용하지 않아도 동작하긴 하던데 이렇게 따로 close state를 관리하신 이유가 있을까요?

2023-12-08 06:19 UTC, nim-od commented on ReactNativeStudy/Eurali/Week2/cameraApp/src/navigators/Stack.tsx
> +          title: curImageInfo?.modificationDate,
이 라이브러리는 수정하지 않은 경우에도 modificationDate를 제공하나요?
제공한다면 creationDate와 동일한 값을 줄텐데 field name이 헷갈립니다.
creationDate, modificationDate를 따로 관리하거나, 두 정보를 포함할 수 있는 네이밍이면 좋을 것 같습니다.

2023-12-08 06:19 UTC, nimod7890 commented on ReactNativeStudy/Eurali/Week2/cameraApp/src/navigators/Stack.tsx
> +      <Stack.Screen
이 스크린은 어떤 경우에 접근하고 무슨 역할을 하나요? 
저도 구현하려했는데 어디에 쓰이는지 모르겠더라고요

2023-12-08 06:19 UTC, nimod7890 commented on ReactNativeStudy/Eurali/Week2/cameraApp/src/navigators/Stack.tsx
> +          headerLeft: () => (
page 뒤로가기 부분은 직접 구현하지 않고 기본 기능을 활용해도 좋을 것 같아요.
아니면 직접 구현하신 이유가 있을까요? 스타일링..?

2023-12-08 06:19 UTC, nimod7890 commented on ReactNativeStudy/Eurali/Week2/cameraApp/src/screens/Home.tsx
> +      {images.length > 0 && (
length >0, length===0 경우를 나눠 구현하신 이유가 궁급합니다.
엠제이와 같은 이유..??

2023-12-08 06:19 UTC, nimod7890 commented on ReactNativeStudy/Eurali/Week2/cameraApp/src/store/index.tsx
> +export type imageType = {
물론 프로젝트 범위가 작아서 그렇게 안하셨겠지만
image type은 types/image.ts 와 같이 분리해 관리하는 것을 추천드립니다!

2023-12-08 06:19 UTC, nimod7890 commented on ReactNativeStudy/Eurali/Week2/cameraApp/src/utils/gradientText.tsx
디테일 다 챙기셨군요. 대단하십니다

2023-12-08 06:19 UTC, nimod7890 commented on ReactNativeStudy/Eurali/Week2/cameraApp/src/utils/requestPermissions.tsx
> +  if (os === 'android') {
지금은 두개밖에 안되긴 하지만 확장성을 위해 switch 도 괜찮아보입니다!

2023-12-08 11:45 UTC, coddingyun commented on ReactNativeStudy/Eurali/Week2/cameraApp/src/App.tsx
> +  const isHome = useStore(state => state.isHome);
<Tab.Navigator> 내부 말씀하시는 걸까요?
해당 부분에 위치시켜보았는데, Error: A navigator can only contain 'Screen', 'Group' or 'React.Fragment' as its direct children (found 'AddButton'). To render this component in the navigator, pass it in the 'component' prop to 'Screen'. 이런 에러가 나서 포기했었습니다..!

2023-12-08 11:45 UTC, coddingyun commented on ReactNativeStudy/Eurali/Week2/cameraApp/src/App.tsx
> +        {/* <TabNavigation /> */}
감사합니다 :)

2023-12-08 11:47 UTC, coddingyun commented on ReactNativeStudy/Eurali/Week2/cameraApp/src/components/AddButton.tsx
> +const {width} = Dimensions.get('window');
width가 Home, AddButton 컴포넌트에서 사용되어서 constants로 관리하는 것이 좋을 것 같네요! 감사합니다

2023-12-08 11:48 UTC, coddingyun commented on ReactNativeStudy/Eurali/Week2/cameraApp/src/components/AddButton.tsx
> +  const handleClickAdd = () => {
함수명으로 기능이 명확해지는 점이 좋더라구요!

2023-12-08 11:50 UTC, coddingyun commented on ReactNativeStudy/Eurali/Week2/cameraApp/src/components/BottomSheet.tsx
> +        onChange={handleSheetChanges}
정말 클린하지 않은 코드이긴 한데... 기능을 동작하게 하려고, 사용자가 bottom sheet를 내려서 index가 0이되면 아예 bottom sheet를 display: none을 주기위해 사용하였습니다!

2023-12-08 11:51 UTC, coddingyun commented on ReactNativeStudy/Eurali/Week2/cameraApp/src/screens/Home.tsx
> +      {images.length > 0 && (
네 ㅎㅎ 저도 중첩 삼항연산자로 고생한 기억이 많아서 이번에 적용해보았습니다.

2023-12-08 11:51 UTC, coddingyun commented on ReactNativeStudy/Eurali/Week2/cameraApp/src/store/index.tsx
> +export type imageType = {
참조하겠습니다!

2023-12-08 11:51 UTC, coddingyun commented on ReactNativeStudy/Eurali/Week2/cameraApp/src/utils/requestPermissions.tsx
> +  if (os === 'android') {
넵 참조하겠습니다!

2023-12-08 11:53 UTC, coddingyun commented on ReactNativeStudy/Eurali/Week2/cameraApp/src/utils/gradientText.tsx
하다가 포기한 흔적이 남은 거였어요...ㅠ 파일을 지웠어야 했는데..! 이 김에 한번 내일까지 도전해보겠습니다..ㅎㅎ

2023-12-09 06:44 UTC, yeonju0110 approved these changes
이번주도 고생하셨습니다 🥹

2023-12-09 06:45 UTC, merged