[3주차] 브리즈 과제 제출합니다.
cmc-14th-web/ReactNativeStudy pull request #24
Opened 2023-12-14 11:59 UTC by suminhan123

#### 사용
전역 상태로 recoil을 사용했고, style은 StyleSheet 사용했습니다.

#### 이슈
이전 과제와 같이 프로젝트를 생성했지만 이번에는 gradle과 jdk 버전 충돌로 자꾸 빌드 에러가 났습니다.
stack overflow 참고해서 jdk 버전도 바꿔보고 android studio에서 버전 수정도 해보고...환경 변수도 바꿔보고.. 했지만 해결하지 못했습니다..
(그래서 이전 과제 프로젝트에서 이번 기능을 추가하여 구현하였습니다.)

#### 해결 못한 기능
동영상 실행 기능은 아직 구현 못하였습니다.

2023-12-15 07:53 UTC, nimod7890 requested changes

2023-12-15 07:53 UTC, nimod7890 commented on ReactNativeStudy/Breeze/Week3/CameraPictureApp/src/apis/getPlayList.ts
> +  const url = `https://www.googleapis.com/youtube/v3/videos?part=snippet&chart=mostPopular&maxResults=${maxResults}&key=${Config.API_KEY}`;
getPlayList와 getSearchPlaylist 간 중복되는 부분 (baseURL, header 등) 따로 통합해서 사용해도 좋을 것 같아요!

2023-12-15 07:53 UTC, nimod7890 commented on ReactNativeStudy/Breeze/Week3/CameraPictureApp/src/apis/getPlayList.ts
> +export const getPlayList = async (maxResults = 25): Promise<any[]> => {
getPlayList보다는 getPopularPlayList 와 같은 네이밍이 api 목적에 부합해보입니다.

2023-12-15 07:53 UTC, nimod7890 commented on ReactNativeStudy/Breeze/Week3/CameraPictureApp/src/apis/getPlayList.ts
> +    const response = await fetch(url, options);
reactQuery 사용힌 error handling 도 추천드립니다

2023-12-15 07:53 UTC, nimod7890 commented on ReactNativeStudy/Breeze/Week3/CameraPictureApp/src/components/Video.tsx
> +    <View style={styles.container}>
detail page 구현하다보니 Video의 하단 description? 이 재사용되더라고요 
적절히 컴포넌트 분리해보는 것도 좋을 것 같아요

2023-12-15 07:53 UTC, nimod7890 commented on ReactNativeStudy/Breeze/Week3/CameraPictureApp/src/components/SearchHeader.tsx
> +    stackNavigation.navigate('SearchHome');
아하 search 동작하는 페이지와 search 결과를 띄워주는 페이지를 분리하셨군요

2023-12-15 07:53 UTC, nimod7890 commented on ReactNativeStudy/Breeze/Week3/CameraPictureApp/src/styles/ColorPalette.ts
> +    100: '#F5F5F5',
이렇게 해도 gray.100 같이 접근되나요???

2023-12-15 07:53 UTC, nimod7890 commented on ReactNativeStudy/Breeze/Week3/CameraPictureApp/src/screens/index.ts
> +export {default as DetailScreen} from './DetailScreen';
배럴 자동으로 해주는 익스텐션 진짜 필요하지 않나요 ㅋㅋㅋㅋㅋㅋ 하나하나 쓰기 너무 번거로워요

2023-12-15 07:53 UTC, nimod7890 commented on ReactNativeStudy/Breeze/Week3/CameraPictureApp/src/screens/SearchHomeScreen.tsx
> +    'searchVideos',
queryKey에 searchText도 배열 형태로 함께 넣으면 좋을 것 같아요!

2023-12-15 07:53 UTC, nimod7890 commented on ReactNativeStudy/Breeze/Week3/CameraPictureApp/src/screens/HomeScreen.tsx
> +  const videoData = data?.map(item => {
video data가 늘 해당 type으로 사용된다면, api 나 api를 감싼 query hook부분에서 parsing 해주는 것도 좋을 것 같습니다

2023-12-15 12:58 UTC, suminhan123 commented on ReactNativeStudy/Breeze/Week3/CameraPictureApp/src/apis/getPlayList.ts
> +  const url = `https://www.googleapis.com/youtube/v3/videos?part=snippet&chart=mostPopular&maxResults=${maxResults}&key=${Config.API_KEY}`;
저도 axios instance를 만드는 게 좋을 것 같네요! 감사합니다!

2023-12-15 12:59 UTC, suminhan123 commented on ReactNativeStudy/Breeze/Week3/CameraPictureApp/src/styles/ColorPalette.ts
> +    100: '#F5F5F5',
저는 palette.gray[100]이렇게 사용했어요!

2023-12-19 16:51 UTC, yeonju0110 approved these changes
고생하셨습니다 !! 😊

2023-12-19 16:51 UTC, merged